version: '3.8'
services:
  bank-mssql-db:
    container_name: bank-mssql-db
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Mfcatl007
    volumes:
      - bank-mssql-db:/var/opt/mssql
  bank-service:
    container_name: bank-service
    build: ./bank-service
    ports:
      - "8080:8080"
  atm-service:
    container_name: atm-service
    build: ./atm-service
    ports:
      - "8081:8081"
volumes:
  bank-mssql-db: