package com.egc.atmservice.domain.exception;

public enum ExceptionMassage {
    SESSION_ALREADY_EXISTS,
    SESSION_DOES_NOT_EXISTS,
    CARD_NOT_INSERTED,
    NOT_AUTHENTICATED,
    PIN_CODE_AUTHENTICATION_NOT_AVAILABLE,
    FINGER_PRINT_AUTHENTICATION_NOT_AVAILABLE,
    UNEXPECTED_ERROR
}
