spring:
  application:
    name: bank-service
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=bank;trustServerCertificate=true
    username: sa
    password: Mfcatl007

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2016Dialect
  sql:
    init:
      mode: always



jwt:
  key: =MjWP5L7CiDesAWDswWDseWAdefesfawdawdawdawbgrtdbzgzdrgdzrgzdrgrdznfxnhfxnftxnftxnftntf
  issuer: 'bank-service'